FROM ubuntu:14.04

RUN sudo apt-get install -y wget
RUN wget https://downloads.plex.tv/plex-media-server/0.9.15.1.1639-26325ea/plexmediaserver_0.9.15.1.1639-26325ea_amd64.deb
RUN dpkg -i plexmediaserver_0.9.15.1.1639-26325ea_amd64.deb


EXPOSE 32400
