FROM paimpozhil/dock-x2go-lxde

RUN apt-get install -y mono-devel
RUN mkdir -p /usr/lib/rider
RUN wget http://download.jetbrains.com/resharper/riderRS-144.5342.tar.gz
RUN tar -xvf riderRS-144.5342.tar.gz -C /usr/lib/rider 
